"""
Tests for the Job Marketplace API.

Organized in two groups: job endpoints, then application endpoints. Within
each group, the happy path comes first, followed by the error cases —
that's the order you'd want to read them in to understand what the
endpoint is supposed to do before seeing how it's supposed to fail.

Run with:
    pytest
or, on Windows, if `pytest` isn't found on your PATH:
    py -m pytest
"""

from fastapi.testclient import TestClient


# ---------------------------------------------------------------------------
# Jobs
# ---------------------------------------------------------------------------

def test_create_job_returns_201_with_open_status(client: TestClient):
    response = client.post(
        "/jobs",
        json={"title": "Data Analyst", "description": "Analyse data.", "location": "Kuala Lumpur"},
    )

    assert response.status_code == 201
    body = response.json()
    assert body["title"] == "Data Analyst"
    assert body["status"] == "OPEN"
    # id and created_at are generated by the server — just confirm they exist.
    assert "id" in body
    assert "created_at" in body


def test_create_job_rejects_missing_fields(client: TestClient):
    # No "location" — should fail validation before ever reaching business logic.
    response = client.post(
        "/jobs",
        json={"title": "Data Analyst", "description": "Analyse data."},
    )
    assert response.status_code == 422


def test_get_job_returns_the_job(client: TestClient, open_job: dict):
    response = client.get(f"/jobs/{open_job['id']}")
    assert response.status_code == 200
    assert response.json()["id"] == open_job["id"]


def test_get_job_returns_404_for_unknown_id(client: TestClient):
    response = client.get("/jobs/11111111-1111-1111-1111-111111111111")
    assert response.status_code == 404


def test_list_jobs_returns_everything_by_default(client: TestClient, open_job: dict):
    client.post(
        "/jobs",
        json={"title": "Second Job", "description": "desc", "location": "Remote"},
    )
    response = client.get("/jobs")
    assert response.status_code == 200
    assert len(response.json()) == 2


def test_list_jobs_can_filter_by_status(client: TestClient, open_job: dict):
    client.post(
        "/jobs",
        json={"title": "Second Job", "description": "desc", "location": "Remote"},
    )
    client.post(f"/jobs/{open_job['id']}/close")

    open_jobs = client.get("/jobs", params={"status": "OPEN"}).json()
    closed_jobs = client.get("/jobs", params={"status": "CLOSED"}).json()

    assert len(open_jobs) == 1
    assert len(closed_jobs) == 1
    assert closed_jobs[0]["id"] == open_job["id"]


def test_close_job_sets_status_closed(client: TestClient, open_job: dict):
    response = client.post(f"/jobs/{open_job['id']}/close")
    assert response.status_code == 200
    assert response.json()["status"] == "CLOSED"


def test_close_job_is_idempotent(client: TestClient, open_job: dict):
    """Closing an already-closed job should succeed again, not error —
    the caller's intent ('this job should be closed') is already met."""
    first_close = client.post(f"/jobs/{open_job['id']}/close")
    second_close = client.post(f"/jobs/{open_job['id']}/close")

    assert first_close.status_code == 200
    assert second_close.status_code == 200
    assert second_close.json()["status"] == "CLOSED"


def test_close_unknown_job_returns_404(client: TestClient):
    response = client.post("/jobs/11111111-1111-1111-1111-111111111111/close")
    assert response.status_code == 404


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

def test_submit_application_returns_201(client: TestClient, open_job: dict):
    response = client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "jane@example.com"},
    )

    assert response.status_code == 201
    body = response.json()
    assert body["job_id"] == open_job["id"]
    assert body["candidate_name"] == "Jane Doe"
    assert "id" in body
    assert "submitted_at" in body


def test_submit_application_rejects_invalid_email(client: TestClient, open_job: dict):
    response = client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "not-an-email"},
    )
    assert response.status_code == 422


def test_submit_application_to_unknown_job_returns_404(client: TestClient):
    response = client.post(
        "/jobs/11111111-1111-1111-1111-111111111111/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "jane@example.com"},
    )
    assert response.status_code == 404


def test_submit_application_to_closed_job_returns_409(client: TestClient, open_job: dict):
    """The one real business rule in this API: a closed job must reject
    new applications."""
    client.post(f"/jobs/{open_job['id']}/close")

    response = client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "jane@example.com"},
    )

    assert response.status_code == 409


def test_list_applications_for_job(client: TestClient, open_job: dict):
    client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "jane@example.com"},
    )
    client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "John Smith", "candidate_email": "john@example.com"},
    )

    response = client.get(f"/jobs/{open_job['id']}/applications")

    assert response.status_code == 200
    assert len(response.json()) == 2


def test_list_applications_only_returns_matching_job(client: TestClient, open_job: dict):
    """Applications to a different job shouldn't show up in this job's list."""
    other_job = client.post(
        "/jobs",
        json={"title": "Other Job", "description": "desc", "location": "Remote"},
    ).json()

    client.post(
        f"/jobs/{open_job['id']}/applications",
        json={"candidate_name": "Jane Doe", "candidate_email": "jane@example.com"},
    )
    client.post(
        f"/jobs/{other_job['id']}/applications",
        json={"candidate_name": "John Smith", "candidate_email": "john@example.com"},
    )

    response = client.get(f"/jobs/{open_job['id']}/applications")

    assert response.status_code == 200
    assert len(response.json()) == 1
    assert response.json()[0]["candidate_name"] == "Jane Doe"


def test_list_applications_for_unknown_job_returns_404(client: TestClient):
    response = client.get("/jobs/11111111-1111-1111-1111-111111111111/applications")
    assert response.status_code == 404
